### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by noskincz** [SlightlySimple/FNF-Restructure-Engine#5]
so its me again with the same mod port for fun. I added the characters and one of them was a modified bf sprite and it has kinda replaced ALL bf sprites across all songs/mods so yeah. idk how to fix it, max that the main character file would search for the folder placement of the xml/spritesheet

edit: it also swapped all the poses so the miss poses are played when i hit a note and the normal poses are played whrn i miss a note

**Comment by SlightlySimple** [comment]
Mods replacing files from the base game and other mods is intentional. If you don't want that to happen, you could either rename the spritesheet or put it in a different folder inside the "characters" folder, then assign it to a new character by opening the character it's meant to replace in the Character Editor and clicking "Create Copy"

**Comment by noskincz** [comment]
ahh ok, thanks for explaining
